# Generated by Django 4.1.10 on 2023-07-13 13:29

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Заголовок')),
                ('description_short', models.TextField(default='', verbose_name='Краткое описание')),
                ('description_long', tinymce.models.HTMLField(default='', verbose_name='Подробное Описание')),
                ('lng', models.DecimalField(decimal_places=14, max_digits=17)),
                ('lat', models.DecimalField(decimal_places=14, max_digits=17)),
            ],
            options={
                'ordering': ['title'],
                'unique_together': {('title', 'lng', 'lat')},
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядковый номер')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='web_app.place')),
            ],
            options={
                'ordering': ['order', 'place'],
            },
        ),
    ]
